### PR TITLE
Fixed start and end bug

### PR DESCRIPTION
**Pull request by ultimate-tester**
Makes sure the start and end are now correctly determined. It tries to keep the "current page button" in the middle of all page buttons. Also no more lower than zero browsing.
Also fixed up the test to correctly test this behavior.

### CODE REVIEW

**Comment by niftylettuce** [comment]
@ultimate-tester can you explain what this pull request does?  how was it not correct before and how is it correct now?

**Comment by ultimate-tester** [comment]
Certainly. The current version has the getArrayPages function that returns a function that returns all pages. There is an optional limit to limit the amount of buttons (or pages) to be returned. If you set this limit to 3 (for instance.. This could be any number) and the actual total amount of pages is HIGHER than 3, then every page after page 3 will cause the number of buttons to increase. You are on page 4, then this means you have 4 buttons. Page 5 will have 5 buttons, page 6 will have 6 etc. etc. etc.

My fix correctly follows the limit. Set it to 3, and it will always return 3 pages with the current page in the middle of them. To demonstrate, let's say you are on page number 2 and have limit set to 3. This will be returned:

[1] **[2]** [3]

So actually this brings 2 new things. A correct limit, and the current page always being the middle one of the buttons shown.

**Comment by niftylettuce** [comment]
Perfect!

**Comment by niftylettuce** [comment]
I released v0.2.1 to NPM just now!  `npm i --save express-paginate@0.2.1`

Thank you so much @ultimate-tester for your contributions, fixed tests, and explanations 😄

**Pull request merged**
